# Travis CI integration
language: c
compiler:
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "iFll6pD0lzVYVRUlbPBGOTB0xqoEsC0BeUdftfRQdnEssruWOEKtf3VH6gSNRu8QMPeTCNhl4fsWUJhnowZgoobi/XcsXxFv/oJQZ1sa7cQUXizeEYUmsDZxUiw/sNsWlUz6dBKPepQStYyOK/tJLQ1GfLi1ESTPt6anokMVDbk="

addons:
  coverity_scan:
    project:
      name: "troglobit/editline"
      description: "Minix editline"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./configure --enable-sigstop --enable-terminal-bell"
    build_command:   "make -j5"
    branch_pattern: master

script: ./configure --enable-sigstop --enable-terminal-bell && make -j5
